_BASE_: [
  '../../fcos/fcos_r50_fpn_1x_coco.yml',
]
log_iter: 1
snapshot_epoch: 200
weights: output/dt_semi_010_fcos_r50_fpn_1x_coco/model_final
# when export model for deploy, just keep _BASE_ and `dataset config`
# Then comment all the other config component (global,model,data_aug,other)


### global config
semi_supervised: True
semi_start_steps: 30 #3000 #5000
use_ema: True
use_meanteacher: True
ema_decay: 0.9996
ema_decay_type: None
ema_start_steps: 30 #1000 #3000

save_interval: &save_interval 5000
eval_interval: &eval_interval 2000

SSOD: DenseTeacher
DenseTeacher:
  train_cfg:
    ratio: 0.01
    sup_weight: 1.0
    unsup_weight: 1.0
    suppress: linear
    loss_weight: {distill_loss_cls: 4.0, distill_loss_box: 1.0, distill_loss_quality: 1.0}
    gamma: 2.0
  test_cfg: 
    #inference_on: teacher
    inference_on: student # simple eval
  weakAug:
    - NormalizeImage: {mean: [103.53, 116.28, 123.675], std: [1.0, 1.0, 1.0], is_scale: False}
  strongAug:
    #- AugmentationUTStrong: {}
    - NormalizeImage: {mean: [103.53, 116.28, 123.675], std: [1.0, 1.0, 1.0], is_scale: False}
  sup_batch_transforms:
    - Permute: {}
    - PadBatch: {pad_to_stride: 32}
    - Gt2FCOSTarget:
        object_sizes_boundary: [64, 128, 256, 512]
        center_sampling_radius: 1.5
        downsample_ratios: [8, 16, 32, 64, 128]
        norm_reg_targets: True
  unsup_batch_transforms:
    - Permute: {}
    - PadBatch: {pad_to_stride: 32}

# [11/14 13:09:24] ppdet.engine INFO: Epoch: [0] [0/4] learning_rate: 0.010000 loss: 1.439103 loss_cls: 0.544091 loss_box: 0.295228 loss_quality: 0.599783 loss_sup_sum: 1.439103 distill_l
# oss_cls: 0.000000 distill_loss_box: 0.000000 distill_loss_quality: 0.000000 loss_unsup_sum: 0.000000 fg_sum: 0.000000 eta: 1:05:57 batch_cost: 4.1220 data_cost: 0.0267 ips: 0.4852 image
# s/s
# [11/14 13:09:25] ppdet.engine INFO: Epoch: [0] [1/4] learning_rate: 0.010000 loss: 1.365707 loss_cls: 0.475117 loss_box: 0.288099 loss_quality: 0.602491 loss_sup_sum: 1.365707 distill_l
# oss_cls: 0.000000 distill_loss_box: 0.000000 distill_loss_quality: 0.000000 loss_unsup_sum: 0.000000 fg_sum: 0.000000 eta: 0:45:40 batch_cost: 1.5933 data_cost: 0.0058 ips: 1.2553 image
# s/s
# [11/14 13:09:27] ppdet.engine INFO: Epoch: [0] [2/4] learning_rate: 0.010000 loss: 1.280249 loss_cls: 0.528689 loss_box: 0.228016 loss_quality: 0.523544 loss_sup_sum: 1.280249 distill_l
# oss_cls: 0.000000 distill_loss_box: 0.000000 distill_loss_quality: 0.000000 loss_unsup_sum: 0.000000 fg_sum: 0.000000 eta: 0:41:04 batch_cost: 2.0019 data_cost: 0.0057 ips: 0.9991 image
# s/s
# [11/14 13:09:29] ppdet.engine INFO: Epoch: [0] [3/4] learning_rate: 0.010000 loss: 1.520947 loss_cls: 0.509235 loss_box: 0.356194 loss_quality: 0.655518 loss_sup_sum: 1.520947 distill_l
# oss_cls: 0.000000 distill_loss_box: 0.000000 distill_loss_quality: 0.000000 loss_unsup_sum: 0.000000 fg_sum: 0.000000 eta: 0:38:06 batch_cost: 1.8406 data_cost: 0.0043 ips: 1.0866 image
# s/s
# [11/14 13:09:34] ppdet.engine INFO: Epoch: [1] [0/4] learning_rate: 0.010000 loss: 1.013959 loss_cls: 0.286764 loss_box: 0.206192 loss_quality: 0.521002 loss_sup_sum: 1.013959 distill_l
# oss_cls: 0.000000 distill_loss_box: 0.000000 distill_loss_quality: 0.000000 loss_unsup_sum: 0.000000 fg_sum: 0.000000 eta: 0:44:04 batch_cost: 4.2723 data_cost: 0.8883 ips: 0.4681 image
# s/s

### dataset config
metric: COCO
num_classes: 80
TrainDataset:
  !SemiCOCODataSet
    image_dir: val2017
    anno_path: annotations/instances_val2017_8img.json
    dataset_dir: /paddle/dataset/coco
    data_fields: ['image', 'gt_bbox', 'gt_class', 'is_crowd']

UnsupTrainDataset:
  !SemiCOCODataSet
    image_dir: val2017
    anno_path: annotations/instances_val2017_8img.json
    dataset_dir: /paddle/dataset/coco
    data_fields: ['image']
    supervised: False

EvalDataset:
  !COCODataSet
    image_dir: val2017
    #anno_path: annotations/instances_val2017_8img.json
    anno_path: annotations/instances_val2017.json
    dataset_dir: /paddle/dataset/coco

TestDataset:
  !ImageFolder
    anno_path: annotations/instances_val2017.json # also support txt (like VOC's label_list.txt)
    dataset_dir: /paddle/dataset/coco # if set, anno_path will be 'dataset_dir/anno_path'


### data_aug config
worker_num: 2 # set 0 for single gpu debug
SupTrainReader:
  sample_transforms:
    - Decode: {}
    - RGBReverse: {}
    - Resize: {target_size: [800, 1333], keep_ratio: True, interp: 1}
    #- RandomResize: {target_size: [[640, 1333], [672, 1333], [704, 1333], [736, 1333], [768, 1333], [800, 1333]], keep_ratio: True, interp: 1}
    #- RandomFlip: {}
  batch_size: 2
  shuffle: True
  drop_last: True


UnsupTrainReader:
  sample_transforms:
    - Decode: {}
    - RGBReverse: {}
    - Resize: {target_size: [800, 1333], keep_ratio: True, interp: 1}
    #- RandomResize: {target_size: [[640, 1333], [672, 1333], [704, 1333], [736, 1333], [768, 1333], [800, 1333]], keep_ratio: True, interp: 1}
    #- RandomFlip: {}
  batch_size: 2
  shuffle: True
  drop_last: False


EvalReader:
  sample_transforms:
    - Decode: {}
    - RGBReverse: {}
    - Resize: {target_size: [800, 1333], keep_ratio: True, interp: 1}
    - NormalizeImage: {mean: [103.53, 116.28, 123.675], std: [1.0, 1.0, 1.0], is_scale: False}
    - Permute: {}
  batch_transforms:
    - PadBatch: {pad_to_stride: 32}
  batch_size: 1 # must be 1
# bgr.pdparams + RGBReverse  8img 41.7  all 18.9
# bgr.pdparams   8img 39.8  all 16.6

TestReader:
  sample_transforms:
    - Decode: {}
    - RGBReverse: {}
    - Resize: {target_size: [800, 1333], keep_ratio: True, interp: 1}
    - NormalizeImage: {mean: [103.53, 116.28, 123.675], std: [1.0, 1.0, 1.0], is_scale: False}
    - Permute: {}
  batch_transforms:
    - PadBatch: {pad_to_stride: 32}
  batch_size: 1 # must be 1


### other config
epoch: 240
LearningRate:
  base_lr: 0.01
  schedulers:
  - !PiecewiseDecay
    gamma: 0.1
    milestones: [240]
    use_warmup: False # True
  - !LinearWarmup
    start_factor: 0.001
    steps: 500

OptimizerBuilder:
  optimizer:
    momentum: 0.9
    type: Momentum
  regularizer:
    factor: 0.0001
    type: L2
  clip_grad_by_norm: 1.0



### model config
architecture: FCOS
#pretrain_weights: https://paddledet.bj.bcebos.com/models/pretrained/ResNet50_cos_pretrained.pdparams
pretrain_weights: /paddle/cvpods_fcos_5k_bgr.pdparams # 18.9
#norm_type: sync_bn

FCOS:
  backbone: ResNet
  neck: FPN
  fcos_head: FCOSHead

ResNet:
  depth: 50
  variant: 'a' #
  norm_type: bn
  freeze_at: 0 # res2
  return_idx: [1, 2, 3]
  num_stages: 4

FPN:
  out_channel: 256
  spatial_scales: [0.125, 0.0625, 0.03125]
  extra_stage: 2
  has_extra_convs: True
  use_c5: False

FCOSHead:
  fcos_feat:
    name: FCOSFeat
    feat_in: 256
    feat_out: 256
    num_convs: 4
    norm_type: "gn"
    use_dcn: False
  fpn_stride: [8, 16, 32, 64, 128]
  prior_prob: 0.01
  norm_reg_targets: True
  centerness_on_reg: True
  num_shift: 0 #
  sqrt_score: True #
  fcos_loss:
    name: FCOSLoss
    loss_alpha: 0.25
    loss_gamma: 2.0
    iou_loss_type: "giou"
    reg_weights: 1.0
    quality: "iou" #
  nms:
    name: MultiClassNMS
    nms_top_k: 1000
    keep_top_k: 100
    score_threshold: 0.05 #0.025
    nms_threshold: 0.6
