# soft_teacher: SoftTeacher
ssod: LabelMatch
label_match: True
update_interval: 100
# norm_type: sync_bn
LabelMatch:
  debug: False
  use_mining: True
  momentum: 0.996
  teacher: FasterRCNN
  student: FasterRCNNLM
  train_cfg: 
    use_teacher_proposal: False
    pseudo_label_initial_score_thr: 0.5
    rpn_pseudo_threshold: 0.85
    cls_pseudo_threshold: 0.85
    reg_pseudo_threshold: 0.02
    jitter_times: 10
    jitter_scale: 0.06
    min_pseduo_box_size: 0
    unsup_weight: 2.5
  test_cfg:
    inference_on: student

architecture: FasterRCNN
pretrain_teacher_weights: /root/mnt_z/ztt/paddle-detection/work_dir/faster_rcnn_40epoch/weights/faster_rcnn_r50_fpn_1x_coco/38.pdparams
use_ema: true
ema_decay: 0.999
# /root/mnt_z/ztt/pretrain/faster_rcnn_r50_fpn_2x_coco.pdparams

architecture: FasterRCNNLM
pretrain_student_weights: /root/mnt_z/ztt/paddle-detection/work_dir/faster_rcnn_40epoch/weights/faster_rcnn_r50_fpn_1x_coco/38.pdparams
use_ema: true
ema_decay: 0.999

FasterRCNN:
  backbone: ResNet
  neck: FPN
  rpn_head: RPNHead
  bbox_head: BBoxHead
  # post process
  bbox_post_process: BBoxPostProcess

FasterRCNNLM:
  backbone: ResNet
  neck: FPN
  rpn_head: RPNHead
  bbox_head: BBoxHeadLM
  # post process
  bbox_post_process: BBoxPostProcess

ResNet:
  # index 0 stands for res2
  depth: 50
  norm_type: bn
  freeze_at: 0
  return_idx: [0,1,2,3]
  num_stages: 4

FPN:
  out_channel: 256

RPNHead:
  anchor_generator:
    aspect_ratios: [0.5, 1.0, 2.0]
    anchor_sizes: [[32], [64], [128], [256], [512]]
    strides: [4, 8, 16, 32, 64]
  rpn_target_assign:
    batch_size_per_im: 256
    fg_fraction: 0.5
    negative_overlap: 0.3
    positive_overlap: 0.7
    use_random: True
  train_proposal:
    min_size: 0.0
    nms_thresh: 0.7
    pre_nms_top_n: 2000
    post_nms_top_n: 1000
    topk_after_collect: True
  test_proposal:
    min_size: 0.0
    nms_thresh: 0.7
    pre_nms_top_n: 1000
    post_nms_top_n: 1000


BBoxHead:
  head: TwoFCHead
  roi_extractor:
    resolution: 7
    sampling_ratio: 0
    aligned: True
  bbox_assigner: BBoxAssigner

BBoxAssigner:
  batch_size_per_im: 512
  bg_thresh: 0.5
  fg_thresh: 0.5
  fg_fraction: 0.25
  use_random: True

BBoxHeadLM:
  head: TwoFCHeadLM
  roi_extractor:
    resolution: 7
    sampling_ratio: 0
    aligned: True
  bbox_assigner: BBoxAssignerLM

BBoxAssignerLM:
  batch_size_per_im: 512
  bg_thresh: 0.5
  fg_thresh: 0.5
  fg_fraction: 0.25
  use_random: True

TwoFCHead:
  out_channel: 1024

TwoFCHeadLM:
  out_channel: 1024

BBoxPostProcess:
  decode: RCNNBox
  nms:
    name: MultiClassNMS
    keep_top_k: 100
    score_threshold: 0.05
    nms_threshold: 0.5
