_BASE_: [
  '../datasets/coco_detection.yml',
  '../runtime.yml',
  #'_base_/optimizer_3x.yml',
  '_base_/dino_focalnet.yml',
  '_base_/dino_reader.yml',
  #'_base_/yoloe_reader.yml',
]

weights: output/dino_focalnet_large_fl4_3x_coco/model_final
find_unused_parameters: True
log_iter: 100
snapshot_epoch: 1
#pretrain_weights: https://bj.bcebos.com/v1/paddledet/models/pretrained/focalnet_large_lrf_384_fl4_pretrained.pdparams
pretrain_weights: https://bj.bcebos.com/v1/paddledet/models/pretrained/focalnet_large_fl4_pretrained_on_o365.pdparams


FocalNet:
  arch: 'focalnet_L_384_22k_fl4'
  out_indices: [0, 1, 2, 3]

DINOTransformer:
  num_levels: 5


epoch: 36
LearningRate:
  base_lr: 0.0001
  schedulers:
  - !PiecewiseDecay
    gamma: 0.1
    milestones: [33]
    use_warmup: false

OptimizerBuilder:
  clip_grad_by_norm: 0.1
  regularizer: false
  optimizer:
    type: AdamW
    weight_decay: 0.0001
