_BASE_: [
  '../datasets/coco_detection.yml',
  '../runtime.yml',
  '_base_/optimizer_1x.yml',
  '_base_/dino_r50.yml',
  '_base_/dino_reader.yml',
]

weights: output/dino_r18_4scale_1x_coco/model_final
find_unused_parameters: True
log_iter: 100
snapshot_epoch: 1

architecture: DETR
pretrain_weights: https://bj.bcebos.com/v1/paddledet/models/pretrained/ResNet18_torch_pretrained.pdparams
hidden_dim: 256
use_focal_loss: True

DETR:
  backbone: ResNet
  transformer: DINOTransformer
  detr_head: DINOHead
  post_process: DETRBBoxPostProcess

ResNet:
  # index 0 stands for res2
  depth: 18
  norm_type: bn
  freeze_at: 0
  return_idx: [1, 2, 3]
  lr_mult_list: [0.0, 0.1, 0.1, 0.1]
  num_stages: 4
