_BASE_: [
  '../../datasets/coco_detection.yml',
  '../../runtime.yml',
  '../_base_/optimizer_12e.yml',
  '../_base_/dino_r50vd_pan.yml',
  '../_base_/yoloe_reader.yml',
]

weights: output/dino_r50vd_pan_3_0_6_1x_coco/model_final
find_unused_parameters: True
log_iter: 100
snapshot_epoch: 1


pretrain_weights: https://paddledet.bj.bcebos.com/models/pretrained/ResNet50_vd_ssld_v2_pretrained.pdparams
for_distill: True
