_BASE_: [
  '../datasets/coco_detection.yml',
  '../runtime.yml',
  '_base_/optimizer_1x.yml',
  '_base_/faster_rcnn_r50_fpn.yml',
  '_base_/faster_fpn_reader.yml',
]
weights: output/softteacher_coco_010/model_final

label_match: false
ssod: SoftTeacher
update_interval: 1000
find_unused_parameters: true

num_classes: 80

TrainDataset:
  !COCODataSet
    image_dir: train2017
    anno_path: annotations/semi_supervised/instances_train2017.1@10.json
    dataset_dir: /paddle/dataset/coco
    data_fields: ['image', 'gt_bbox', 'gt_class']

TrainDataset_sup:
  !Semi_COCODataSet
    image_dir: train2017
    anno_path: annotations/semi_supervised/instances_train2017.1@10.json
    dataset_dir: /paddle/dataset/coco
    data_fields: ['image', 'gt_bbox', 'gt_class']
    # allow_empty: True

TrainDataset_unsup:
  !Semi_COCODataSet
    image_dir: train2017
    anno_path: annotations/semi_supervised/instances_train2017.1@10-unlabeled.json
    dataset_dir: /paddle/dataset/coco
    data_fields: ['image', 'gt_bbox', 'gt_class']
    allow_empty: True

EvalDataset:
  !COCODataSet
    image_dir: val2017
    anno_path: annotations/instances_val2017.json
    dataset_dir: /paddle/dataset/coco
TestDataset:
  !ImageFolder
    anno_path: annotations/instances_val2017.json
    dataset_dir: /paddle/dataset/coco

Semi_TrainReader:
  sample_transforms:
    - Decode: {}
    # - RandomResize: {target_size: [[800, 1333]], interp: 2, keep_ratio: True}
    - RandomResize: {target_size: [[640, 1333], [672, 1333], [704, 1333], [736, 1333], [768, 1333], [800, 1333]], interp: 2, keep_ratio: True}
    - RandomFlip: {prob: 0.5}
    - AutoAugment: {autoaug_type: weak}
    - NormalizeImage: {is_scale: true, mean: [0.485,0.456,0.406], std: [0.229, 0.224,0.225]}
    - Permute: {}
  batch_transforms:
    - PadBatch: {pad_to_stride: 32}
  unsup_tea_transforms:
    - Decode: {}
    # - RandomResize: {target_size: [[800, 1333]], interp: 2, keep_ratio: True}
    - RandomResize: {target_size: [[640, 1333], [672, 1333], [704, 1333], [736, 1333], [768, 1333], [800, 1333]], interp: 2, keep_ratio: True}
    - RandomFlip: {prob: 0.5}
    - NormalizeImage: {is_scale: true, mean: [0.485,0.456,0.406], std: [0.229, 0.224,0.225]}
    - Permute: {}
  unsup_stu_transforms:
    - Decode: {}
    - RandomResize: {target_size: [[640, 1333], [672, 1333], [704, 1333], [736, 1333], [768, 1333], [800, 1333]], interp: 2, keep_ratio: True}
    - RandomFlip: {prob: 0.5}
    - AutoAugment: {autoaug_type: strong}
    - RandomErasingImage: {}
    - NormalizeImage: {is_scale: true, mean: [0.485,0.456,0.406], std: [0.229, 0.224,0.225]}
    - Permute: {}
  batch_size: 2
  shuffle: true
  drop_last: true
  collate_batch: false
  epoch_length: 1800
  sample_ratio: [1, 4]

epoch: 8
eval_interval: 50
LearningRate:
  base_lr: 0.005
  schedulers:
  - !PiecewiseDecay
    gamma: 0.1
    milestones: [5, 7]
  - !LinearWarmup
    start_factor: 0.1
    steps: 1000

log_iter: 10
use_ema: True
ema_decay: 0.999
pretrain_weights: ../faster_rcnn_r50_fpn_2x_coco_010_26.0.pdparams

SoftTeacher:
  teacher: FasterRCNN
  student: FasterRCNN
  train_cfg: 
    use_teacher_proposal: False
    pseudo_label_initial_score_thr: 0.5
    rpn_pseudo_threshold: 0.8
    cls_pseudo_threshold: 0.8
    reg_pseudo_threshold: 0.03
    jitter_times: 10
    jitter_scale: 0.06
    min_pseduo_box_size: 0
    unsup_weight: 2.5
  test_cfg:
    inference_on: student
