_BASE_: [
  '../datasets/coco_detection.yml',
  '../runtime.yml',
  '_base_/optimizer_1x.yml',
  '_base_/faster_rcnn_r50_fpn.yml',
  '_base_/faster_fpn_reader.yml',
]
weights: output/zhongyi/model_final

update_interval: 1000
save_interval: 2000
num_classes: 24
manual_length: &manual_length 200 
epoch_length: &epoch_length 2000
eval_interval: &eval_interval 2000
batch_size: &batch_size 8

LabelMatch:
  debug: True
  interval: 500

TrainDataset:
  !COCODataSet
    image_dir: biaojian/object_detection_data/1103_hunhe_class_24/train/images
    anno_path: coco_data/labeled_data/annotations/coco_24_each_class10_total240.json
    dataset_dir: /root/mnt2/ztt/dataset
    data_fields: ['image', 'gt_bbox', 'gt_class']

TrainDatasetLM:
  !LMCocoDataset
    image_dir: biaojian/object_detection_data/1103_hunhe_class_24/train/images
    anno_path: coco_data/unlabeled_data/annotations/unlabeled_train_sub.json
    dataset_dir:  /root/mnt2/ztt/dataset
    data_fields: ['image', 'gt_bbox', 'gt_class']
    manual_length: *manual_length

TrainDataset_sup:
  !Semi_COCODataSet
    image_dir: biaojian/object_detection_data/1103_hunhe_class_24/train/images
    anno_path: coco_data/labeled_data/annotations/coco_24_each_class10_total240.json
    dataset_dir: /root/mnt2/ztt/dataset
    data_fields: ['image', 'gt_bbox', 'gt_class']
    # allow_empty: True

TrainDataset_unsup:
  !Semi_COCODataSet
    image_dir: biaojian/object_detection_data/1103_hunhe_class_24/train/images
    anno_path: coco_data/unlabeled_data/annotations/unlabeled_train_sub.json
    dataset_dir: /root/mnt2/ztt/dataset/
    data_fields: ['image', 'gt_bbox', 'gt_class']
    allow_empty: True

EvalDataset:
  !COCODataSet
    image_dir: images
    anno_path: /root/mnt2/ztt/dataset/biaojian/object_detection_data/1103_hunhe_class_24/val/coco_24.json
    dataset_dir: /root/mnt2/ztt/dataset/biaojian/object_detection_data/1103_hunhe_class_24/val

TestDataset:
  !ImageFolder
    anno_path: /root/mnt2/ztt/dataset/biaojian/object_detection_data/1103_hunhe_class_24/val/coco_24.json
    dataset_dir: /root/mnt2/ztt/dataset/biaojian/object_detection_data/1103_hunhe_class_24/val

# Semi_TrainEqualReader:
Semi_TrainReader: 
  sample_transforms:
    - Decode: {}
    # - RandomResize: {target_size: [[500, 1333], [800, 1333]], interp: 2, keep_ratio: True}
    - ResizeStepScaling: {img_scale: [1024, 1024], ratio_range: [0.5, 1.5], interp: 2, keep_ratio: True}
    - RandomFlip: {prob: 0.5}
    - NormalizeImage: {is_scale: true, mean: [0.485,0.456,0.406], std: [0.229, 0.224,0.225]}
    - Permute: {}
  batch_transforms:
  - PadBatch: {pad_to_stride: 32}
  unsup_tea_transforms:
    - Decode: {}
    - RandomResize: {target_size: [[512, 1333], [544, 1333], [576, 1333], [608, 1333], [640, 1333], [672, 1333], [704, 1333], [736, 1333], [768, 1333], [800, 1333]], interp: 2, keep_ratio: True}
    - RandomFlip: {prob: 0.5}
    - NormalizeImage: {is_scale: true, mean: [0.485,0.456,0.406], std: [0.229, 0.224,0.225]}
    - Permute: {}
  unsup_stu_transforms:
    - Decode: {}
    # - RandomResize: {target_size: [[500, 1333], [800, 1333]], interp: 2, keep_ratio: True}
    - ResizeStepScaling: {img_scale: [1024, 1024], ratio_range: [0.5, 1.5], interp: 2, keep_ratio: True}
    - RandomFlip: {prob: 0.5}
    - AugmentationUTStrong: {}
    # - RandomErasingImage: {prob: 0.5, scale: [0.05, 0.2], aspect_ratio: [0.3, 3.3], value: 'random'}
    - RandomErasingImage: {prob: 0.7, scale: [0.05, 0.2], aspect_ratio: [0.3, 3.3], value: 'random'}
    - RandomErasingImage: {prob: 0.5, scale: [0.02, 0.2], aspect_ratio: [0.1, 6], value: 'random'}
    - RandomErasingImage: {prob: 0.3, scale: [0.02, 0.2], aspect_ratio: [0.05, 8], value: 'random'}
    - NormalizeImage: {is_scale: true, mean: [0.485,0.456,0.406], std: [0.229, 0.224,0.225]}
    - Permute: {}
  batch_size: *batch_size
  shuffle: true
  drop_last: true
  collate_batch: false
  epoch_length: *epoch_length
  sample_ratio: [1, 1]

epoch: 10
eval_interval: *eval_interval
LearningRate:
  base_lr: 0.001
  schedulers:
  - !PiecewiseDecay
    gamma: 0.1
    milestones: [6, 8]
  - !LinearWarmup
    start_factor: 0.1
    steps: 1000

log_iter: 50
use_ema: True
ema_decay: 0.996
ema_decay_type: constant
pretrain_teacher_weights: /root/mnt2/ltq/projects/PaddleDetection/work_dir/biaojian_fewshot/coco/240/faster_rcnn_resnet50_72epoch/weights/faster_rcnn_r50_fpn_1x_coco_240/best_model.pdparams
pretrain_student_weights: /root/mnt2/ltq/projects/PaddleDetection/work_dir/biaojian_fewshot/coco/240/faster_rcnn_resnet50_72epoch/weights/faster_rcnn_r50_fpn_1x_coco_240/best_model.pdparams
# 'https://paddledet.bj.bcebos.com/models/pretrained/ResNet50_cos_pretrained.pdparams'

# LabelMatch:
#   momentum: 0.9996

BBoxPostProcess:
  nms:
    score_threshold: 0.001