_BASE_: [
  '../datasets/coco_detection.yml',
  '../runtime.yml',
  '_base_/optimizer_1x.yml',
  '_base_/faster_rcnn_r50_fpn.yml',
  '_base_/faster_fpn_reader.yml',
]
weights: output/zhongyi/model_final

update_interval: 1000
save_interval: 2000
num_classes: 2

TrainDataset:
  !COCODataSet
    image_dir: images
    anno_path: /root/mnt2/ztt/SoftTeacher/data/annotations/sup_train_100_new.json
    dataset_dir: /root/mnt2/ltq/datasets/zhongyi/label_data/train
    data_fields: ['image', 'gt_bbox', 'gt_class']

TrainDatasetLM:
  !LMCocoDataset
    image_dir: label_data
    anno_path: /root/mnt2/ltq/datasets/zhongyi/label_data/train_10000_noannotations.json
    dataset_dir: /root/mnt2/ltq/datasets/zhongyi
    data_fields: ['image', 'gt_bbox', 'gt_class']
    manual_length: 1000

TrainDataset_sup:
  !Semi_COCODataSet
    image_dir: images
    anno_path: /root/mnt2/ztt/SoftTeacher/data/annotations/sup_train_100_new.json
    dataset_dir: /root/mnt2/ltq/datasets/zhongyi/label_data/train
    data_fields: ['image', 'gt_bbox', 'gt_class']
    # allow_empty: True

TrainDataset_unsup:
  !Semi_COCODataSet
    image_dir: label_data
    # anno_path: /root/mnt2/ztt/SoftTeacher/data/annotations/unsup.json
    anno_path: /root/mnt2/ltq/datasets/zhongyi/label_data/train_10000_noannotations.json
    dataset_dir: /root/mnt2/ltq/datasets/zhongyi
    data_fields: ['image', 'gt_bbox', 'gt_class']
    allow_empty: True

EvalDataset:
  !COCODataSet
    image_dir: images
    anno_path: /root/mnt2/ztt/SoftTeacher/data/annotations/test.json
    dataset_dir: /root/mnt2/ltq/datasets/zhongyi/label_data/val_0326

TestDataset:
  !ImageFolder
    anno_path: /root/mnt2/ztt/SoftTeacher/data/annotations/test.json
    dataset_dir: /root/mnt2/ltq/datasets/zhongyi/label_data/val_0326

Semi_TrainReader: 
  sample_transforms:
    - Decode: {}
    # - RandomResize: {target_size: [[500, 1333], [800, 1333]], interp: 2, keep_ratio: True}
    - ResizeStepScaling: {img_scale: [1024, 1024], ratio_range: [0.5, 1.5], interp: 2, keep_ratio: True}
    - RandomFlip: {prob: 0.5}
    - NormalizeImage: {is_scale: true, mean: [0.485,0.456,0.406], std: [0.229, 0.224,0.225]}
    - Permute: {}
  batch_transforms:
  - PadBatch: {pad_to_stride: 32}
  unsup_tea_transforms:
    - Decode: {}
    - RandomResize: {target_size: [[500, 1333], [800, 1333]], interp: 2, keep_ratio: True}
    - RandomFlip: {prob: 0.5}
    - NormalizeImage: {is_scale: true, mean: [0.485,0.456,0.406], std: [0.229, 0.224,0.225]}
    - Permute: {}
  unsup_stu_transforms:
    - Decode: {}
    # - RandomResize: {target_size: [[500, 1333], [800, 1333]], interp: 2, keep_ratio: True}
    - ResizeStepScaling: {img_scale: [1024, 1024], ratio_range: [0.5, 1.5], interp: 2, keep_ratio: True}
    - RandomFlip: {prob: 0.5}
    - AugmentationUTStrong: {}
    - RandomErasingImage: {prob: 0.5, scale: [0.05, 0.2], aspect_ratio: [0.3, 3.3], value: 'random'}
    # - RandomErasingImage: {prob: 0.7, scale: [0.05, 0.2], aspect_ratio: [0.3, 3.3], value: 'random'}
    # - RandomErasingImage: {prob: 0.5, scale: [0.02, 0.2], aspect_ratio: [0.1, 6], value: 'random'}
    # - RandomErasingImage: {prob: 0.3, scale: [0.02, 0.2], aspect_ratio: [0.05, 8], value: 'random'}
    - NormalizeImage: {is_scale: true, mean: [0.485,0.456,0.406], std: [0.229, 0.224,0.225]}
    - Permute: {}
  batch_size: 8
  shuffle: true
  drop_last: true
  collate_batch: false
  epoch_length: 2450
  sample_ratio: [1, 1]

epoch: 10
eval_interval: 2000
LearningRate:
  base_lr: 0.001
  schedulers:
  - !PiecewiseDecay
    gamma: 0.1
    milestones: [6, 8]
  - !LinearWarmup
    start_factor: 0.1
    steps: 1000

log_iter: 50
use_ema: True
ema_decay: 0.996
ema_decay_type: constant
pretrain_teacher_weights: /root/mnt2/ltq/projects/PaddleDetection/work_dir/zhongyi/coco/resnet_100/weights/faster_rcnn_r50_fpn_1x_coco_sup100/best_model.pdparams
pretrain_student_weights: 'https://paddledet.bj.bcebos.com/models/faster_rcnn_r50_fpn_2x_coco.pdparams'
# 'https://paddledet.bj.bcebos.com/models/pretrained/ResNet50_cos_pretrained.pdparams'

SoftTeacher:
  teacher: FasterRCNN
  student: FasterRCNN
  train_cfg: 
    use_teacher_proposal: False
    pseudo_label_initial_score_thr: 0.5
    rpn_pseudo_threshold: 0.85
    cls_pseudo_threshold: 0.85
    reg_pseudo_threshold: 0.02
    jitter_times: 10
    jitter_scale: 0.06
    min_pseduo_box_size: 0
    unsup_weight: 2.5
  test_cfg:
    inference_on: student


# export CUDA_VISIBLE_DEVICES=0,1,2,3 && python -m paddle.distributed.launch \
# --log_dir work_dir/zhongyi/130_faster_rcnn_resnet50_soft/log \
# --gpus 0,1,2,3 tools/train.py \
# -c configs/faster_rcnn/zhongyi.yml \
# --use_vdl=true \
# --vdl_log_dir=work_dir/zhongyi/130_faster_rcnn_resnet50_soft/vdl \
# --eval -o weights=work_dir/zhongyi/130_faster_rcnn_resnet50_soft/model_final \
# save_dir=work_dir/zhongyi/130_faster_rcnn_resnet50_soft/weights