_BASE_: [
  '../../datasets/coco_detection.yml',
  '../../runtime.yml',
  '../../fcos/_base_/fcos_r50_fpn.yml',
  '../../fcos/_base_/optimizer_1x.yml',
  #'../../fcos/_base_/fcos_reader.yml',
]

weights: output/fcos_r50_fpn_multiscale_2x_coco/model_final

worker_num: 2
TrainReader:
  sample_transforms:
    - Decode: {}
    - RandomResize: {target_size: [[640, 1333], [672, 1333], [704, 1333], [736, 1333], [768, 1333], [800, 1333]], keep_ratio: True, interp: 1}
    # - Resize: {target_size: [800, 1333], keep_ratio: True, interp: 1}
    - NormalizeImage: {mean: [103.53, 116.28, 123.675], std: [1.0, 1.0, 1.0], is_scale: False}
    - RandomFlip: {}
  batch_transforms:
    - Permute: {}
    - PadBatch: {pad_to_stride: 32} #
    - Gt2FCOSTarget:
        object_sizes_boundary: [64, 128, 256, 512]
        center_sampling_radius: 1.5
        downsample_ratios: [8, 16, 32, 64, 128]
        norm_reg_targets: True
  batch_size: 2
  shuffle: True
  drop_last: True


EvalReader:
  sample_transforms:
    - Decode: {}
    - RGBReverse: {} # must, and no need to turn back
    - Resize: {target_size: [800, 1333], keep_ratio: True, interp: 1} # 18.3  41.3
    #- ResizeShortestEdge: {short_edge_length: 800, max_size: 1333, sample_style: "choice"} # 16.4  41.4
    - NormalizeImage: {mean: [103.53, 116.28, 123.675], std: [1.0, 1.0, 1.0], is_scale: False}
    - Permute: {}
  batch_transforms:
    - PadBatch: {pad_to_stride: 32} # 41.0
  batch_size: 1 # must be 1


# EvalReader:
#   sample_transforms:
#     - Decode: {}
#     - RGBReverse: {} # must, and no need to turn back
#     - Resize: {target_size: [800, 1333], keep_ratio: True, interp: 1}
#     #- ResizeShortestEdge: {short_edge_length: 800, max_size: 1333, sample_style: "choice"}
#     - NormalizeImage: {mean: [103.53, 116.28, 123.675], std: [1.0, 1.0, 1.0], is_scale: False}
#     - Permute: {}
#   batch_transforms:
#     - PadBatch: {pad_to_stride: 32}
#   batch_size: 1


TestReader:
  sample_transforms:
    - Decode: {}
    - Resize: {target_size: [800, 1333], keep_ratio: True, interp: 1}
    - NormalizeImage: {mean: [0.485, 0.456, 0.406], std: [0.229, 0.224, 0.225], is_scale: True}
    - Permute: {}
  batch_transforms:
    - PadBatch: {pad_to_stride: 128}
  batch_size: 1
  fuse_normalize: True


epoch: 24
LearningRate:
  base_lr: 0.01
  schedulers:
  - !PiecewiseDecay
    gamma: 0.1
    milestones: [16, 22]
  - !LinearWarmup
    start_factor: 0.001
    steps: 1000


TrainDataset:
  !COCODataSet
    image_dir: train2017
    anno_path: annotations/semi_supervised/instances_train2017.1@10.json
    dataset_dir: /paddle/dataset/coco
    data_fields: ['image', 'gt_bbox', 'gt_class']

EvalDataset:
  !COCODataSet
    image_dir: val2017
    anno_path: annotations/instances_val2017.json
    #anno_path: annotations/instances_val2017_8img.json
    dataset_dir: /paddle/dataset/coco





architecture: FCOS
pretrain_weights: https://paddledet.bj.bcebos.com/models/pretrained/ResNet50_cos_pretrained.pdparams
#norm_type: sync_bn

FCOS:
  backbone: ResNet
  neck: FPN
  fcos_head: FCOSHead

ResNet:
  depth: 50
  variant: 'a' #
  norm_type: bn
  freeze_at: 0 # res2
  return_idx: [1, 2, 3]
  num_stages: 4

FPN:
  out_channel: 256
  spatial_scales: [0.125, 0.0625, 0.03125]
  extra_stage: 2
  has_extra_convs: True
  use_c5: False

FCOSHead:
  fcos_feat:
    name: FCOSFeat
    feat_in: 256
    feat_out: 256
    num_convs: 4
    norm_type: "gn"
    use_dcn: False
  fpn_stride: [8, 16, 32, 64, 128]
  prior_prob: 0.01
  norm_reg_targets: True
  centerness_on_reg: True
  num_shift: 0 #
  sqrt_score: True #
  fcos_loss:
    name: FCOSLoss
    loss_alpha: 0.25
    loss_gamma: 2.0
    iou_loss_type: "giou"
    reg_weights: 1.0
    quality: "iou" #
  nms:
    name: MultiClassNMS
    nms_top_k: 1000
    keep_top_k: 100
    score_threshold: 0.05 #0.025
    nms_threshold: 0.6
