_BASE_: [
  '../../fcos/fcos_r50_fpn_iou_multiscale_2x_coco.yml',
]
weights: output/fcos_r50_fpn_coco_sup010/model_final
pretrain_weights: https://bj.bcebos.com/v1/paddledet/models/pretrained/ResNet50_va_caffe_bgr_pretrained.pdparams
log_iter: 20
snapshot_epoch: 1

TrainDataset:
  !COCODataSet
    image_dir: train2017
    anno_path: semi_annotations/instances_train2017.1@10.json
    dataset_dir: dataset/coco
    data_fields: ['image', 'gt_bbox', 'gt_class']


epoch: 24
LearningRate:
  base_lr: 0.01
  schedulers:
  - !PiecewiseDecay
    gamma: 0.1
    milestones: [16, 22]
  - !LinearWarmup
    start_factor: 0.3333333333333333
    steps: 500
  # - !LinearWarmup
  #   start_factor: 0.001
  #   steps: 1000


TrainReader:
  sample_transforms:
    - Decode: {}
    - RGBReverse: {}
    - RandomResize: {target_size: [[640, 1333], [672, 1333], [704, 1333], [736, 1333], [768, 1333], [800, 1333]], keep_ratio: True, interp: 1}
    #- NormalizeImage: {mean: [0.485, 0.456, 0.406], std: [0.229, 0.224, 0.225], is_scale: True}
    - NormalizeImage: {mean: [103.53, 116.28, 123.675], std: [1.0, 1.0, 1.0], is_scale: False}
    - RandomFlip: {}
  batch_transforms:
    - Permute: {}
    - PadBatch: {pad_to_stride: 32}
    - Gt2FCOSTarget:
        object_sizes_boundary: [64, 128, 256, 512]
        center_sampling_radius: 1.5
        downsample_ratios: [8, 16, 32, 64, 128]
        norm_reg_targets: True
  batch_size: 2
  shuffle: True
  drop_last: True


EvalReader:
  sample_transforms:
    - Decode: {}
    - RGBReverse: {}
    - Resize: {target_size: [800, 1333], keep_ratio: True, interp: 1}
    #- NormalizeImage: {mean: [0.485, 0.456, 0.406], std: [0.229, 0.224, 0.225], is_scale: True}
    - NormalizeImage: {mean: [103.53, 116.28, 123.675], std: [1.0, 1.0, 1.0], is_scale: False}
    - Permute: {}
  batch_transforms:
    - PadBatch: {pad_to_stride: 32}
  batch_size: 1


TestReader:
  sample_transforms:
    - Decode: {}
    - RGBReverse: {}
    - Resize: {target_size: [800, 1333], keep_ratio: True, interp: 1}
    #- NormalizeImage: {mean: [0.485, 0.456, 0.406], std: [0.229, 0.224, 0.225], is_scale: True}
    - NormalizeImage: {mean: [103.53, 116.28, 123.675], std: [1.0, 1.0, 1.0], is_scale: False}
    - Permute: {}
  batch_transforms:
    - PadBatch: {pad_to_stride: 32}
  batch_size: 1
  fuse_normalize: True


ResNet:
  depth: 50
  variant: 'a' #
  norm_type: bn
  freeze_at: 0 # res2
  return_idx: [1, 2, 3]
  num_stages: 4


FCOSHead:
  fcos_feat:
    name: FCOSFeat
    feat_in: 256
    feat_out: 256
    num_convs: 4
    norm_type: "gn"
    use_dcn: False
  fpn_stride: [8, 16, 32, 64, 128]
  prior_prob: 0.01
  norm_reg_targets: True
  centerness_on_reg: True
  num_shift: 0 #
  sqrt_score: True #
  fcos_loss:
    name: FCOSLoss
    loss_alpha: 0.25
    loss_gamma: 2.0
    iou_loss_type: "giou"
    reg_weights: 1.0
    quality: "iou" #
  nms:
    name: MultiClassNMS
    nms_top_k: 1000
    keep_top_k: 100
    score_threshold: 0.05 #0.025
    nms_threshold: 0.6
