_BASE_: [
  '../../fcos/fcos_r50_fpn_iou_multiscale_2x_coco.yml',
]
weights: output/fcos_r50_fpn_coco_sup010/model_final
log_iter: 1
snapshot_epoch: 100

TrainDataset:
  !COCODataSet
    image_dir: train2017
    anno_path: annotations/instances_train2017.json
    dataset_dir: dataset/coco
    data_fields: ['image', 'gt_bbox', 'gt_class']


TrainReader:
  sample_transforms:
    - Decode: {}
    - RGBReverse: {}
    - Resize: {target_size: [800, 1333], keep_ratio: True, interp: 1} # 18.3  41.3
    - NormalizeImage:  {mean: [103.53, 116.28, 123.675], std: [1.0, 1.0, 1.0], is_scale: False}
  batch_transforms:
    - Permute: {}
    - PadBatch: {pad_to_stride: 32}
    - Gt2FCOSTarget:
        object_sizes_boundary: [64, 128, 256, 512]
        center_sampling_radius: 1.5
        downsample_ratios: [8, 16, 32, 64, 128]
        norm_reg_targets: True
  batch_size: 4
  shuffle: True
  drop_last: True


EvalReader:
  sample_transforms:
    - Decode: {}
    - RGBReverse: {}
    - Resize: {target_size: [800, 1333], keep_ratio: True, interp: 1} # 18.3  41.3
    - NormalizeImage:  {mean: [103.53, 116.28, 123.675], std: [1.0, 1.0, 1.0], is_scale: False}
    - Permute: {}
  batch_transforms:
    - PadBatch: {pad_to_stride: 32} #
  batch_size: 1 # must be 1

architecture: FCOS
pretrain_weights: cvpods_fcos_5k_bgr.pdparams


FCOS:
  backbone: ResNet
  neck: FPN
  fcos_head: FCOSHead

ResNet:
  depth: 50
  variant: 'a' #
  norm_type: bn
  freeze_at: 0 # res2
  return_idx: [1, 2, 3]
  num_stages: 4

FPN:
  out_channel: 256
  spatial_scales: [0.125, 0.0625, 0.03125]
  extra_stage: 2
  has_extra_convs: True
  use_c5: False

FCOSHead:
  fcos_feat:
    name: FCOSFeat
    feat_in: 256
    feat_out: 256
    num_convs: 4
    norm_type: "gn"
    use_dcn: False
  fpn_stride: [8, 16, 32, 64, 128]
  prior_prob: 0.01
  norm_reg_targets: True
  centerness_on_reg: True
  num_shift: 0 #
  sqrt_score: True #
  fcos_loss:
    name: FCOSLoss
    loss_alpha: 0.25
    loss_gamma: 2.0
    iou_loss_type: "giou"
    reg_weights: 1.0
    quality: "iou" #
  nms:
    name: MultiClassNMS
    nms_top_k: 1000
    keep_top_k: 100
    score_threshold: 0.05 #0.025
    nms_threshold: 0.6



epoch: 240
LearningRate:
  base_lr: 0.01
  schedulers:
  - !PiecewiseDecay
    gamma: 0.1
    milestones: [240]
    use_warmup: True
  - !LinearWarmup
    start_factor: 0.001
    steps: 1000

OptimizerBuilder:
  optimizer:
    momentum: 0.9
    type: Momentum
  regularizer:
    factor: 0.0001
    type: L2