_BASE_: [
  '../../datasets/coco_detection.yml',
  '../../runtime.yml',
  '../_base_/optimizer_1x.yml',
  '../_base_/dino_r50.yml',
  '../_base_/dino_reader.yml',
]

weights: output/dino_r50_4scale_1x_coco/model_final
find_unused_parameters: True
log_iter: 100
snapshot_epoch: 1


architecture: DETR
pretrain_weights: https://paddledet.bj.bcebos.com/models/pretrained/ResNet50_cos_pretrained.pdparams
hidden_dim: 256
use_focal_loss: True


DETR:
  backbone: ResNet
  transformer: DINOTransformer
  detr_head: DINOHead
  post_process: DETRBBoxPostProcess

for_distill: True


worker_num: 4
TrainReader:
  sample_transforms:
    - Decode: {}
    - RandomFlip: {prob: 0.5}
    - RandomSelect: { transforms1: [ RandomShortSideResize: { short_side_sizes: [ 480, 512, 544, 576, 608, 640, 672, 704, 736, 768, 800 ], max_size: 1333 } ],
                      transforms2: [
                          RandomShortSideResize: { short_side_sizes: [ 400, 500, 600 ] },
                          RandomSizeCrop: { min_size: 384, max_size: 600 },
                          RandomShortSideResize: { short_side_sizes: [ 480, 512, 544, 576, 608, 640, 672, 704, 736, 768, 800 ], max_size: 1333 } ]
    }
    - NormalizeImage: {is_scale: true, mean: [0.485, 0.456, 0.406], std: [0.229, 0.224, 0.225]}
    - NormalizeBox: {}
    - BboxXYXY2XYWH: {}
    - Permute: {}
  batch_transforms:
    - PadMaskBatch: {pad_to_stride: -1, return_pad_mask: true}
  batch_size: 2
  shuffle: true
  drop_last: true
  collate_batch: false
  use_shared_memory: false
