worker_num: 2
TrainReader:
  sample_transforms:
  - Decode: {}
  - RandomFlip: {prob: 0.5}
  - RandomSelects: { transforms_list: [
                    [ RandomShortSideResize: { short_side_sizes: [ 480, 512, 544, 576, 608, 640 ], max_size: 640 } ],
                    [ RandomShortSideResize: { short_side_sizes: [ 400, 500, 600 ] },
                      RandomSizeCrop: { min_size: 384, max_size: 600 },
                      RandomShortSideResize: { short_side_sizes: [ 480, 512, 544, 576, 608, 640 ], max_size: 640 } ],
                    [ RandomDistort: {},
                      RandomExpand: { fill_value: [ 123.675, 116.28, 103.53 ] },
                      RandomCrop: {},
                      RandomResize: { target_size: [ 480, 512, 544, 576, 608, 640 ], random_size: True, keep_ratio: True } ] ]
  }
  - NormalizeImage: {is_scale: true, mean: [0.485,0.456,0.406], std: [0.229, 0.224,0.225]}
  - Pad: {size: [640, 640], fill_value: [0., 0., 0.]}
  - NormalizeBox: {}
  - BboxXYXY2XYWH: {}
  - Permute: {}
  batch_size: 2
  shuffle: true
  drop_last: true
  collate_batch: false
  use_shared_memory: false


EvalReader:
  sample_transforms:
  - Decode: {}
  - Resize: {target_size: [640, 640], keep_ratio: True}
  - NormalizeImage: {is_scale: true, mean: [0.485,0.456,0.406], std: [0.229, 0.224,0.225]}
  - Pad: {size: [640, 640], fill_value: [0., 0., 0.]}
  - Permute: {}
  batch_size: 1
  shuffle: false
  drop_last: false


TestReader:
  sample_transforms:
  - Decode: {}
  - Resize: {target_size: [640, 640], keep_ratio: True}
  - NormalizeImage: {is_scale: true, mean: [0.485,0.456,0.406], std: [0.229, 0.224,0.225]}
  - Pad: {size: [640, 640], fill_value: [0, 0, 0]}
  - Permute: {}
  batch_size: 1
  shuffle: false
  drop_last: false
