worker_num: 2
TrainReader:
  sample_transforms:
    - Decode: {}
    #- DecodeCache: {cache_root: 'dataset/coco/cache/buffer'}
    - RandomDistort: {prob: 0.8}
    - RandomExpand: {fill_value: [0., 0., 0.]}
    - RandomCrop: {prob: 0.8}
    - RandomFlip: {}
  batch_transforms:
    - BatchRandomResize: {target_size: [480, 512, 544, 576, 608, 640, 640, 640, 672, 704, 736, 768, 800], random_size: True, random_interp: True, keep_ratio: False}
    - NormalizeImage: {mean: [0., 0., 0.], std: [1., 1., 1.], norm_type: none}
    - NormalizeBox: {}
    - BboxXYXY2XYWH: {}
    - Permute: {}
  batch_size: 2
  shuffle: true
  drop_last: true
  collate_batch: false
  use_shared_memory: false


worker_num: 2
DistillTrainReader:
  sample_transforms:
    - Decode: {}
    #- DecodeCache: {cache_root: 'dataset/coco/cache/buffer'}
    - RandomFlip: {}
  stu_aug:
    - RandomDistort: {prob: 0.8}
    - RandomExpand: {fill_value: [0., 0., 0.]}
    - RandomCrop: {prob: 0.8}
  stu_batch_transforms:
    - BatchRandomResize: {target_size: [480, 512, 544, 576, 608, 640, 640, 640, 672, 704, 736, 768, 800], random_size: True, random_interp: True, keep_ratio: False}
    - NormalizeImage: {mean: [0., 0., 0.], std: [1., 1., 1.], norm_type: none}
    - NormalizeBox: {}
    - BboxXYXY2XYWH: {}
    - Permute: {}
  tea_aug:
    # - Resize: {target_size: [800, 1333], keep_ratio: True}
    - RandomSelect: { transforms1: [ RandomShortSideResize: { short_side_sizes: [ 480, 512, 544, 576, 608, 640, 672, 704, 736, 768, 800 ], max_size: 1333 } ],
                      transforms2: [
                          RandomShortSideResize: { short_side_sizes: [ 400, 500, 600 ] },
                          RandomSizeCrop: { min_size: 384, max_size: 600 },
                          RandomShortSideResize: { short_side_sizes: [ 480, 512, 544, 576, 608, 640, 672, 704, 736, 768, 800 ], max_size: 1333 } ]
    }
    - NormalizeImage: {is_scale: true, mean: [0.485, 0.456, 0.406], std: [0.229, 0.224, 0.225]}
    - NormalizeBox: {}
    - BboxXYXY2XYWH: {}
    - Permute: {}
  tea_batch_transforms:
    - PadMaskBatch: {pad_to_stride: -1, return_pad_mask: true}
  batch_size: 2
  shuffle: True
  drop_last: True
  collate_batch: false
  use_shared_memory: false


EvalReader:
  sample_transforms:
    - Decode: {}
    - Resize: {target_size: [640, 640], keep_ratio: False}
    - NormalizeImage: {mean: [0., 0., 0.], std: [1., 1., 1.], norm_type: none}
    - Permute: {}
  batch_size: 2
  shuffle: false
  drop_last: false


TestReader:
  sample_transforms:
    - Decode: {}
    - Resize: { target_size: [640, 640], keep_ratio: False }
    - NormalizeImage: {mean: [0., 0., 0.], std: [1., 1., 1.], norm_type: none}
    - Permute: {}
  batch_size: 1
  shuffle: false
  drop_last: false
