_BASE_: [
  '../_base_/coco_detection_percent_10.yml',
  '../../runtime.yml',
  '../../deformable_detr/_base_/deformable_optimizer_1x.yml',
  '../../deformable_detr/_base_/deformable_detr_r50.yml',
  '../../deformable_detr/_base_/deformable_detr_reader.yml',
]
eval_interval: 2000
save_interval: 2000
weights: output/dino_r50vd_pan_4_0_6_2x_cocosemi/model_final
find_unused_parameters: True
save_dir: output
log_iter: 20
ssod_method: DenseTeacher
### global config
use_simple_ema: True
ema_decay: 0.9996


### reader config
worker_num: 2
SemiTrainReader:
  sample_transforms:
  - Decode: {}
  - RandomFlip: {prob: 0.5}
  - RandomSelect: { transforms1: [ RandomShortSideResize: { short_side_sizes: [ 480, 512, 544, 576, 608, 640, 672, 704, 736, 768, 800 ], max_size: 640 } ],
                    transforms2: [
                        RandomShortSideResize: { short_side_sizes: [ 400, 500, 600 ] },
                        RandomSizeCrop: { min_size: 384, max_size: 600 },
                        RandomShortSideResize: { short_side_sizes: [ 480, 512, 544, 576, 608, 640, 672, 704, 736, 768, 800 ], max_size: 640 } ]
  }
  weak_aug:
    - NormalizeImage: {is_scale: true, mean: [0.485,0.456,0.406], std: [0.229, 0.224,0.225]}
    - NormalizeBox: {}
    - BboxXYXY2XYWH: {}
    - Permute: {}
  strong_aug:
    - StrongAugImage: {transforms: [
        RandomColorJitter: {prob: 0.8, brightness: 0.4, contrast: 0.4, saturation: 0.4, hue: 0.1},
        RandomErasingCrop: {},
        RandomGaussianBlur: {prob: 0.5, sigma: [0.1, 2.0]},
        RandomGrayscale: {prob: 0.2},
      ]}
    - NormalizeImage: {is_scale: true, mean: [0.485,0.456,0.406], std: [0.229, 0.224,0.225]}
    - NormalizeBox: {}
    - BboxXYXY2XYWH: {}
    - Permute: {}
  sup_batch_transforms:
    # - Permute: {}
   - PadMaskBatch: {pad_to_stride: -1, return_pad_mask: true}
  unsup_batch_transforms:
    # - Permute: {}
   - PadMaskBatch: {pad_to_stride: -1, return_pad_mask: true}
  sup_batch_size: 1
  unsup_batch_size: 1
  shuffle: true
  drop_last: true
  collate_batch: false
  use_shared_memory: false





EvalReader:
  sample_transforms:
  - Decode: {}
  - Resize: {target_size: [800, 1333], keep_ratio: True}
  - NormalizeImage: {is_scale: true, mean: [0.485,0.456,0.406], std: [0.229, 0.224,0.225]}
  - Permute: {}
  batch_transforms:
  - PadMaskBatch: {pad_to_stride: -1, return_pad_mask: true}
  batch_size: 1
  shuffle: false
  drop_last: false

TestReader:
  sample_transforms:
  - Decode: {}
  - Resize: {target_size: [800, 1333], keep_ratio: True}
  - NormalizeImage: {is_scale: true, mean: [0.485,0.456,0.406], std: [0.229, 0.224,0.225]}
  - Permute: {}
  batch_transforms:
  - PadMaskBatch: {pad_to_stride: -1, return_pad_mask: true}
  batch_size: 1
  shuffle: false
  drop_last: false


pretrain_student_weights: https://paddledet.bj.bcebos.com/models/pretrained/ResNet50_vb_normal_pretrained.pdparams
pretrain_teacher_weights: https://paddledet.bj.bcebos.com/models/pretrained/ResNet50_vb_normal_pretrained.pdparams
SSOD: DETR_SSOD
DETR_SSOD:
  teacher: DETR
  student: DETR
  train_cfg:
    sup_weight: 1.0
    unsup_weight: 2.5
    semi_start_iters: 10000
    ema_start_iters: 6000
    pseudo_label_initial_score_thr: 0.7
    min_pseduo_box_size: 0
    # loss_weight: {distill_loss_class: 1.0, distill_loss_bbox: 1.0, distill_loss_giou: 1.0,
    #              distill_loss_class_aux: 1.0,distill_loss_bbox_aux: 1.0,distill_loss_giou_aux: 1.0, 
    #              distill_loss_class_dn: 1.0,distill_loss_bbox_dn: 1.0,distill_loss_giou_dn: 1.0,
    #              distill_loss_class_aux_dn: 1.0,distill_loss_bbox_aux_dn: 1.0,distill_giou_aux_dn: 1.0}
    concat_sup_data: True
    suppress: linear
    ratio: 0.01
    gamma: 2.0
  test_cfg:
    inference_on: teacher






metric: COCO
num_classes: 80

# partial labeled COCO, use `SemiCOCODataSet` rather than `COCODataSet`
TrainDataset:
  !SemiCOCODataSet
    image_dir: train2017
    anno_path: annotations/instances_train2017_rand8.json
    dataset_dir: dataset/coco
    data_fields: ['image', 'gt_bbox', 'gt_class', 'is_crowd']

# partial unlabeled COCO, use `SemiCOCODataSet` rather than `COCODataSet`
UnsupTrainDataset:
  !SemiCOCODataSet
    image_dir: train2017
    anno_path: semi_annotations/instances_train2017.1@5-unlabeled.json
    dataset_dir: dataset/coco
    data_fields: ['image']
    supervised: False

EvalDataset:
  !COCODataSet
    image_dir: val2017
    anno_path: annotations/instances_val2017.json
    dataset_dir: dataset/coco
    allow_empty: true

TestDataset:
  !ImageFolder
    anno_path: annotations/instances_val2017.json # also support txt (like VOC's label_list.txt)
    dataset_dir: dataset/coco # if set, anno_path will be 'dataset_dir/anno_path'

epoch: 240
LearningRate:
  base_lr: 0.0002
  schedulers:
  - !PiecewiseDecay
    gamma: 0.1
    milestones: [200]
    use_warmup: false

OptimizerBuilder:
  clip_grad_by_norm: 0.1
  regularizer: false
  optimizer:
    type: AdamW
    weight_decay: 0.0001
